TESTS = test/*.js
RERORTER = spec
TIMEOUT = 10000
MOCHA_OPTS = 

test:
	@NODE_ENV=test ./node_modules/mocha/bin/mocha \
	--reporter $(RERORTER) \
	--TIMEOUT $(TIMEOUT) \
	$(MOCHA_OPTS) \
	$(TESTS)

test-cov:
	$(MAKE) test MOCHA_OPTS='--require blanket' RERORTER=html-cov > coverage.html

test-all:test test-cov

.PHONY:test